=== Grandez/SDP_Java/SDPLoader/src/main/resources/SDPConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.sdp.com/SDPConfig" 
           xmlns="http://www.sdp.com/SDPConfig">

    <xs:element name="SDPConfig">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="group" minOccurs="0" maxOccurs="unbounded" />
           </xs:sequence>
       </xs:complexType>
    </xs:element>

   <xs:element name="group">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="name"        type="xs:string"/>
          <xs:element name="id"          type="xs:int"/>
          <xs:element ref="item"                            minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
  </xs:element>

   <xs:element name="item">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="name"        type="xs:string"/>
          <xs:element name="value"       type="xs:string"/>
          <xs:element name="type"        type="xs:int"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="min"         type="xs:int"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="max"         type="xs:int"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="mask"        type="xs:string"   minOccurs="0" maxOccurs="1"/>
          <xs:element ref="description"                     minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
  </xs:element>

   <xs:element name="description">
      <xs:complexType>
          <xs:sequence>
             <xs:element name="tooltip" type="xs:string"/>
             <xs:element name="desc"    type="xs:string"/>
          </xs:sequence>
          <xs:attribute type="xs:string" name="lang" use="optional" default="xx"/>
          <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
       </xs:complexType>
  </xs:element>
    
</xs:schema>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/config/SDPConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:SDPConfig xmlns:c="http://www.sdp.com/SDPConfig" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:schemaLocation="http://www.sdp.com/SDPConfig ../SDPConfig.xsd">
   <c:group>
      <name>sdp</name>
      <id>0</id>

      <c:item>
         <name>inst.name</name>
         <value>Serendipity</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>application.base</name>
         <value>1</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>auto.application</name>
         <value>2</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.config</name>
         <value>P:/SDP/config</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.config.relative</name>
         <value>config</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.docs </name>
         <value> P:/SDP/Docs</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>file.ignore</name>
         <value>ignore.txt</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>max.versions</name>
         <value>1</value>
         <type>1</type>
      </c:item>

   </c:group>
   
   <c:group>
      <name>code</name>
      <id>1</id>
      <c:item>
         <name>max.complexity</name>
         <value>15</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>max.complexity.parr</name>
         <value>10</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>max.sentences</name>
         <value>25</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>min.coverage</name>
         <value>75</value>
         <type>1</type>
      </c:item>
   </c:group>
   
   <c:group>
      <name>parser</name>
      <id>2</id> 
      <c:item>
         <name>copy.ext.0</name>
         <value>.</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>copy.ext.1</name>
         <value>.cpy</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>copy.ext.2</name>
         <value>.cbl</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dialect</name>
         <value>ZCobol</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.copy.0</name>
         <value>P:/SDP/BBVA/CPYWRK</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.copy.1</name>
         <value>P:/SDP/BBVA/CPY</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.copy.2</name>
         <value>P:/SDP/BBVA/DCLWRK</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.copy.3</name>
         <value>P:/SDP/BBVA/DCL</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.input</name>
         <value>P:/SDP/BBVA/wrk</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>dir.output</name>
         <value>P:/SDP/BBVA/out</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>flags</name>
         <value>1111111111111111</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>margin.left</name>
         <value>7</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>margin.right</name>
         <value>72</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>save.copys</name>
         <value>true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>save.source</name>
         <value>true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>tab</name>
         <value>1</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>trap.level</name>
         <value>normal</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>tree.depth </name>
         <value>1</value>
         <type>1</type>
      </c:item>
   </c:group>
   
   <c:group>
      <name>profiler</name>
      <id>4</id>
      <c:item>
         <name>call</name>
         <value> true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>cics</name>
         <value> true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>depth</name>
         <value> 9999</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>module</name>
         <value> true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>paragraph</name>
         <value> true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>perform</name>
         <value> true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>profile</name>
         <value>true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>sql</name>
         <value> true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>suspend</name>
         <value>true</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>verify</name>
         <value>false</value>
         <type>1</type>
      </c:item>
    
    </c:group>
    
   <c:group>    
      <name>jms</name>
      <id>5</id>
      <c:item>
         <name>commit.interval</name>
         <value>1</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>group</name>
         <value>10</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>hostname</name>
         <value>localhost</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>port</name>
         <value>1414</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>queue.collector </name>
         <value>SDP.COLLECTOR</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>queue.manager   </name>
         <value>SDP.QMGR</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>queue.output    </name>
         <value>SDP.COLLECTOR</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>queue.parser    </name>
         <value>SDP.PARSER</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>queue.trapper   </name>
         <value>SDP.TRAPPER</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>type</name>
         <value>HTTP</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>url.trapper</name>
         <value>localhost:8080/SDPWebPersister</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>wait</name>
         <value>1</value>
         <type>1</type>
      </c:item>
   </c:group>
    
   <c:group>
       <name>sesion</name>
       <id>6</id>   
      <c:item>
         <name>desv.elapsed</name>
         <value>25</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>desv.input</name>
         <value>10</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>desv.output</name>
         <value>10</value>
         <type>1</type>
      </c:item>
   </c:group>   

   <c:group>
       <name>sgdb</name>
       <id>7</id>   
   
      <c:item>
         <name>name</name>
         <value>mariadb</value>
         <type>1</type>
      </c:item>
   </c:group>

   <c:group>
      <name>web</name>
      <id>3</id>
         
      <c:item>
        <name>log.max.records</name>
        <value>250</value>
        <type>1</type>
      </c:item>
      <c:item>
         <name>log.tms.interval</name>
         <value>1h</value>
         <type>1</type>
      </c:item>
   </c:group>
   
   <c:group>
      <name>ivp</name>
      <id>8</id>

      <c:item>
         <name>config.file</name>
         <value>P:/SDP/Config/ivp.xml</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>input.dir</name>
         <value>P:/SDP/Cobol</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>loader</name>
         <value>IVPLoader</value>
         <type>1</type>
      </c:item>
   </c:group>
   
   <c:group>
      <name>excel</name>
      <id>9</id>
      <c:item>
         <name>concatenate</name>
         <value>$</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>delimiter</name>
         <value>_</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>empty</name>
         <value>TOOLS_EMPTY</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>mask</name>
         <value>/</value>
         <type>1</type>
      </c:item>
      <c:item>
         <name>prefix</name>
         <value>SDP</value>
         <type>1</type>
      </c:item>
   </c:group>
   
</c:SDPConfig>
