=== Grandez/SDP_Java/SDPLoader/src/main/resources/SDPRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.sdp.com/SDPRules" 
           xmlns="http://www.sdp.com/SDPRules">

    <xs:element name="SDPRules">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="header" minOccurs="0" maxOccurs="1" />
               <xs:element ref="group"  minOccurs="0" maxOccurs="unbounded" />
               <xs:element ref="item"   minOccurs="0" maxOccurs="unbounded" />            
           </xs:sequence>
       </xs:complexType>
    </xs:element>

   <xs:element name="header">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="title"   type="xs:string"  minOccurs="0" maxOccurs="1" />
          <xs:element name="replace" type="xs:boolean" minOccurs="0" maxOccurs="1" default="true"/>
          <xs:element name="comment" type="xs:string"  minOccurs="0" maxOccurs="1" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <xs:element name="group">
        <xs:complexType>
    	   <xs:sequence>
               <xs:element name="idGroup"   type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="idParent"  type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="prefix"    type="prefixType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"    type="xs:boolean" minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="title"                        minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="description"                  minOccurs="0" maxOccurs="1"/>

               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>
               <xs:element name="sample"    type="sampleType" minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="item"                         minOccurs="0" maxOccurs="unbounded"  />
           </xs:sequence>
    	   <xs:attribute name="name"  type="nameType" use="required"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="idItem"  type="idType"      minOccurs="0" maxOccurs="1"/>
               <xs:element name="idGroup" type="idType"      minOccurs="0" maxOccurs="1"/>
               <xs:element name="object"  type="objectType"  minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"  type="xs:boolean"  minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="title"                       minOccurs="0" maxOccurs="1"/>
               <xs:element ref="description"                 minOccurs="0" maxOccurs="1"/>
               <xs:element ref="message"                     minOccurs="0" maxOccurs="1"/>
                                             
               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>

               <xs:element name="sample"  type="sampleType"  minOccurs="0" maxOccurs="1"/>
               <xs:element ref="rule"                        minOccurs="0" maxOccurs="unbounded" />
           </xs:sequence>
           <xs:attribute name="name"  type="nameType" use="required"/>
           
       </xs:complexType>
       
    </xs:element>

    <xs:element name="rule">
       <xs:complexType>
            <xs:sequence>
               <xs:element name="idRule"      type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="idItem"      type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="idGroup"     type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="priority"    type="xs:int"        minOccurs="0" maxOccurs="1"   default="0"/>
               <xs:element name="severity"    type="severityType"  minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"      type="xs:boolean"    minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="message"                           minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="description"                       minOccurs="0" maxOccurs="1"/>

               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>              
               <xs:element name="condition"   type="conditionType" minOccurs="0" maxOccurs="1"/>
               <xs:element name="sample"      type="sampleType"    minOccurs="0" maxOccurs="1"/>
           </xs:sequence>
           <xs:attribute name="name"  type="nameType"/>          
       </xs:complexType>
   </xs:element>         

  <xs:element name="message">
    <xs:complexType>
         <xs:sequence>     
            <xs:element name="text" type="textType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="description">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="1">
         <xs:element name="ref" type="idType"/>
         <xs:sequence>     
            <xs:element name="text" type="textType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
      </xs:choice>
      <xs:attribute name="id"  type="idType"  use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="title">
    <xs:complexType>
         <xs:sequence>     
            <xs:element name="text" type="titleType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
    </xs:complexType>
  </xs:element>

   <xs:complexType name="objectType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="type"  type="subObject"   use="optional"/>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

   <xs:complexType name="conditionTypeList">
      <xs:sequence>
          <xs:element name="condition" type="conditionType" minOccurs="1" maxOccurs="unbounded"  />
      </xs:sequence>
   </xs:complexType>
   
   <xs:complexType name="textType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="lang"    use="optional" default="xx"/>
            <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  
   <xs:complexType name="titleType">
       <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="lang"    use="optional" default="xx"/>
            <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
         </xs:extension>         
      </xs:simpleContent>
  </xs:complexType>
  
   <xs:simpleType name="severityType">
       <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="5"/>
       </xs:restriction>
   </xs:simpleType>


   <xs:complexType name="conditionType">
          <xs:sequence>
             <xs:element ref="message" minOccurs="0" maxOccurs="1"/>
             <xs:choice minOccurs="0" maxOccurs="1">
                 <xs:element name="lvalue"          type="operandType"/>
                 <xs:element name="script"          type="scriptType"/>
                 <xs:element name="type"            type="lvalueType"/>
                 <xs:element name="configuration"   type="xs:string"/>
             </xs:choice>
             <xs:element name="operator"            type="operatorType"  minOccurs="0" maxOccurs="1"/>      
             <xs:choice minOccurs="0" maxOccurs="1">
                 <xs:element name="property"        type="xs:string"/>
                 <xs:element name="attribute"       type="xs:string"/>
                 <xs:element name="method"          type="xs:string"/>
                 <xs:element name="expression"      type="xs:string"/>
                 <xs:element name="value"           type="xs:string"/>
                 <xs:element name="rvalue"          type="xs:string"/>
                 <xs:element name="rscript"         type="scriptType"/>                 
             </xs:choice>

         </xs:sequence>

      <xs:attribute name="negated" use="optional"   type="xs:boolean"  default="false"/>   
   </xs:complexType>

   <xs:simpleType name="subObject">
       <xs:restriction base="xs:string">
          <xs:enumeration value="verb"/>
          <xs:enumeration value="option"/>
          <xs:enumeration value="lvalue"/>
          <xs:enumeration value="rvalue"/>
          <xs:enumeration value="list"/>
       </xs:restriction>
   </xs:simpleType>
    
   <xs:simpleType name="lvalueType">
       <xs:restriction base="xs:string">
          <xs:enumeration value="string"/>
          <xs:enumeration value="integer"/>
          <xs:enumeration value="long"/>
          <xs:enumeration value="decimal"/>
          <xs:enumeration value="boolean"/>
          <xs:enumeration value="date"/>
          <xs:enumeration value="time"/>
          <xs:enumeration value="timestamp"/>          
          <xs:enumeration value="verb"/>
          <xs:enumeration value="option"/>
          <xs:enumeration value="lvalue"/>
          <xs:enumeration value="rvalue"/>
          <xs:enumeration value="value"/>
       </xs:restriction>
   </xs:simpleType>


   <xs:complexType name="operandType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="type" use="optional" default="value">
                <xs:simpleType>
                   <xs:restriction base="xs:string">
                      <xs:enumeration value="attribute"/>
                      <xs:enumeration value="configuration"/>
                      <xs:enumeration value="expression"/>
                      <xs:enumeration value="function"/>
                      <xs:enumeration value="method"/>
                      <xs:enumeration value="option"/>
                      <xs:enumeration value="property"/>                      
                      <xs:enumeration value="value"/>
                      <xs:enumeration value="variable"/>
                  </xs:restriction>
               </xs:simpleType>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
   
   <xs:simpleType name="operatorType">
      <xs:annotation>
         <xs:documentation>
             Comparator apply to object and value in form:
             object comparator value
             Comparator can be one of following keywords
                * ==       - Equal
                * >        - Greater than
                * &lt;        - Less than
                * >=       - Greater or equal than
                * &lt;=       - Less or equal than
                * start    - Object start with 'value' sequence
                * contains - Object contains 'value' sequence
                * match    - Object math the regular expression specified in 'value'
         </xs:documentation>
      </xs:annotation>
      <xs:union memberTypes="operatorTypeL operatorTypeU" />
   </xs:simpleType>


         <xs:simpleType name="operatorTypeL">
            <xs:restriction base="xs:string">
               <xs:enumeration value="mandatory"/>
               <xs:enumeration value="equal"/>
               <xs:enumeration value="eq"/>          
               <xs:enumeration value="is"/>          
               <xs:enumeration value="gt"/>
               <xs:enumeration value="lt"/>
               <xs:enumeration value="ge"/>
               <xs:enumeration value="le"/>
               <xs:enumeration value="start"/>
               <xs:enumeration value="end"/>
               <xs:enumeration value="contains"/>
               <xs:enumeration value="match"/>
               <xs:enumeration value="has"/>
           </xs:restriction>
       </xs:simpleType>
         <xs:simpleType name="operatorTypeU">
            <xs:restriction base="xs:string">
               <xs:enumeration value="MANDATORY"/>
               <xs:enumeration value="EQUAL"/>
               <xs:enumeration value="EQ"/>          
               <xs:enumeration value="IS"/>          
               <xs:enumeration value="GT"/>
               <xs:enumeration value="LT"/>
               <xs:enumeration value="GE"/>
               <xs:enumeration value="LE"/>
               <xs:enumeration value="START"/>
               <xs:enumeration value="END"/>
               <xs:enumeration value="CONTAINS"/>
               <xs:enumeration value="MATCH"/>
               <xs:enumeration value="HAS"/>
           </xs:restriction>
       </xs:simpleType>         

   <xs:complexType name="scriptType">
      <xs:sequence>
          <xs:element name="name"        type="xs:string"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="code"        type="xs:string"      minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>   
   </xs:complexType>

   <xs:complexType name="sampleType">
      <xs:sequence>
          <xs:element name="description" type="textType"       minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="correct"     type="xs:string"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="bad"         type="xs:string"      minOccurs="0" maxOccurs="1"/>
      </xs:sequence>   
   </xs:complexType>

   <xs:simpleType name="nameType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
      </xs:restriction>
  </xs:simpleType>
  
   <xs:simpleType name="prefixType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
         <xs:maxLength value="3" />
      </xs:restriction>
  </xs:simpleType>

   <xs:simpleType name="idType">
      <xs:restriction base="xs:long"/>
  </xs:simpleType>
  
</xs:schema>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1200_grp_cmt.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas lexicas / Comentarios</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CMT">
      <idGroup>12</idGroup>
      <idParent>10</idParent>
      <prefix>CMT</prefix>
      <active>true</active>
      <r:title>
          <text>Comentarios</text>      
      </r:title>
      
      <r:description>
          <text>
             Los comentarios deben ser de la forma "* texto"
          </text>      
      </r:description>
      
      <r:item name="CMT">
         <object>CMT</object>
         <active>true</active>
         <r:description>
            <text lang="xx">Gestion de comentarios</text>
         </r:description>
         
         <r:rule>
            <severity>2</severity>
            <r:description>
               <text lang="xx">Los comentarios {comparator} {value}</text>
            </r:description>
            <condition negated="true">
               <type>string</type>
               <operator>start</operator>
               <value>*</value>
            </condition>        
            <sample>
               <description lang="xx">
               Los comentarios pueden empezar con *,/ o D
               
               Estos dos ultimos afectan a como se imprime el codigo fuente durante la fase de compilacion.   
               Dado que no esta permitido imprimir listados desde el Host, estos tipos de comentarios no deben
               utilizarse
               </description> 
               <correct>
      * ESTE ES UN COMENTARIO CORRECTO           
               </correct>
                            
               <bad>
      / ESTE ES UN COMENTARIO INCORRECTO
      D ESTE ES OTRO COMENTARIO INCORRECTO          
               </bad>

            </sample>                
         </r:rule>
         
         <r:rule>
            <priority>1</priority>
            <severity>2</severity>
            <r:description>
               <text lang="xx">No se deben crear lineas de comentarios aislados</text>
            </r:description>
            <condition>
               <lvalue type="attribute">length</lvalue>
               <operator>equal</operator>
               <value>1</value>
            </condition>        
                
         </r:rule>

         <r:rule>
            <priority>2</priority>         
            <severity>2</severity>
            <r:description>
               <text lang="xx">No usar decoradores</text>
            </r:description>
            <condition>
               <lvalue type="property">isDecorator</lvalue>
               <operator>is</operator>
               <value>true</value>
            </condition>        
                
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1800_grp_div_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>DATA DIVISION</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="DATA">
      <idGroup>18</idGroup>
      <idParent>15</idParent>
      <prefix>DAT</prefix>
      <active>true</active>
      <r:title>
          <text>DATA DIVISION</text>      
      </r:title>

      <r:description>
          <text lang="xx">Reglas de control de environment division</text>      
      </r:description>
      
<!--       <r:item name="DIV_DATA"> -->
<!--          <object>DATA</object> -->
<!--          <active>true</active> -->
<!--          <r:title> -->
<!--              <text>Opciones de DATA DIVISION</text>       -->
<!--          </r:title> -->
         
<!--          <r:description> -->
<!--              <text lang="xx"> -->
<!--                SOURCE y OBJECT COMPUTER son unicamente informativos -->
<!--                No es necesario indicarlos -->
<!--              </text>       -->
<!--          </r:description> -->
<!--          <r:message> -->
<!--                   <text lang="xx" dialect="XX">ENVIRONMENT DIVISION no tiene contenido</text> -->
<!--          </r:message> -->
         
<!--          <r:rule> -->
<!--             <severity>2</severity> -->
<!--             <condition> -->
<!--                <lvalue type="property">numOptions</lvalue> -->
<!--                <operator>eq</operator> -->
<!--                <rvalue>0</rvalue> -->
<!--             </condition>         -->
<!--          </r:rule> -->
         
<!--       </r:item> -->

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1700_grp_div_env.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>ENVIRONMENT DIVISION</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="ENVIRONMENT">
      <idGroup>17</idGroup>
      <idParent>15</idParent>
      <prefix>ENV</prefix>
      <active>true</active>
      <r:title>
          <text>ENVIRONMENT DIVISION</text>      
      </r:title>

      <r:description>
          <text lang="xx">Reglas de control de environment division</text>      
      </r:description>
      
      <r:item name="DIV_ENV">
         <object>ENVIRONMENT</object>
         <active>true</active>
         <r:title>
             <text>Opciones de ENVIRONMENT DIVISION</text>      
         </r:title>
         
         <r:description>
             <text lang="xx">
               SOURCE y OBJECT COMPUTER son unicamente informativos
               No es necesario indicarlos
             </text>      
         </r:description>
         <r:message>
                  <text lang="xx" dialect="XX">ENVIRONMENT DIVISION no tiene contenido</text>
         </r:message>
         
         <r:rule>
            <severity>2</severity>
            <condition>
               <lvalue type="attribute">numOptions</lvalue>
               <operator>eq</operator>
               <rvalue>0</rvalue>
            </condition>        
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_9000_grp_mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas a nivel modulo</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="MOD">
      <idGroup>90</idGroup>     
      <prefix>MOD</prefix>
      <r:title>
          <text>Modulo</text>      
      </r:title>
      
      <r:description>
          <text lang="xx">Reglas globales del modulo</text>      
      </r:description>
      
      <r:item name="ModuleName">
         <object>MODULE</object>
         <active>true</active>
         <r:title>
             <text>Nombre del modulo</text>      
         </r:title>
                  
         <r:description>
            <text lang="xx">El nombre del ejecutable debe coincidir con el del fichero fuente</text>
         </r:description>
         
         <r:rule>
            <severity>5</severity>
            <condition negated="true">
               <lvalue type="attribute">moduleName</lvalue>
               <operator>equal</operator>
               <attribute>fileName</attribute>
            </condition>            
         </r:rule>
      </r:item>
      
      <r:item name="ModuleCount">
         <object>MODULE</object>
         <active>true</active>      
         <r:title>
             <text>Numero de modulos</text>      
         </r:title>
            
         <r:description>
            <text lang="xx">Cada ejecutable se codifica en su propio fichero fuente</text>
         </r:description>
         
         <r:rule>
            <severity>5</severity>
            <condition>
               <lvalue type="attribute">moduleCount</lvalue>
               <operator>equal</operator>
               <rvalue>1</rvalue>
            </condition>            
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_6000_grp_sql.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas de SQL</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="SQL">
      <idGroup>60</idGroup>
      <prefix>SQL</prefix>
      <r:title>
          <text>Calidad de SQL</text>      
      </r:title>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1000_grp_lex.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas lexicas</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="LEX">
      <idGroup>10</idGroup>
      <prefix>LEX</prefix>
      <r:description>
          <text lang="xx">Analisis lexico</text>      
      </r:description>
      
      <r:item name="TAB">
         <object>TAB</object>
         <active>true</active>
         <r:title>
            <text>Caracteres de tabulacion</text>
         </r:title>
         <r:description>
            <text>
              El uso de caracteres de tabulacion puede ser dependiente del codigo de paginas usado
              Puede dar problemas de conversion ASCII/EBCDIC
            </text>
         </r:description>
         <r:message>
            <text>No usar caracteres de tabulacion</text>
         </r:message>
         
         <r:rule>
            <severity>2</severity>
            <condition>
               <property>exist()</property>
            </condition>            
         </r:rule>
      </r:item>

      <r:item name="HEXDATA">
         <object>HEX</object>
         <r:title>
            <text>Valores Hexadecimales</text>
         </r:title>
         
         <r:description>
            <text lang="xx">Usar la codificacion hexadecimal para los caracteres no imprimibles</text>
         </r:description>
         <r:message>
            <text>Usar la codificacion hexadecimal para los caracteres no imprimibles</text>
         </r:message>
            
         <r:rule>
            <severity>2</severity>
            <condition>
               <property>exist</property>
            </condition>            
            <sample>
               <description lang="xx">
                  El uso de caracteres no imprimibles:
                 
                  - Puede ocasionar problemas de conversion de caracteres entre maquinas
                  - Impide ver el codigo exacto que se esta utilizando
               
                  De manera general, cuando sea necesario utilizar caracteres especiales se deben especificar 
                  por sus valores hexadecimales
               </description>
               <correct>
                  01  NON-PRINTABLE.
                      03 TAB-CODE    PIC X(01) VALUE X'05'.           
               </correct>
               <bad>
                  01  NON-PRINTABLE.
                      03 TAB-CODE    PIC X(01) VALUE '\t'.           
               </bad>

            </sample>
         </r:rule>         
      </r:item>
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_0000_grp_sdp.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd">

   <r:header>
      <title>Raiz de las reglas</title>
      <replace>false</replace>
   </r:header>
   
   <r:group name="ROOT">
      <idGroup>0</idGroup>
      <idParent>0</idParent>
      <prefix>SDP</prefix>
      <active>true</active>
      <r:title>
         <text>Raiz de las reglas</text>
      </r:title>
      <r:description>
          <text>Raiz de las reglas</text>      
      </r:description>
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_4000_grp_stmt.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Instrucciones</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="STMT">
      <idGroup>40</idGroup>
      <prefix>STM</prefix>
      <r:title>
          <text>Control de instrucciones</text>      
      </r:title>

      <r:description>
          <text>Control de instrucciones</text>      
      </r:description>
   </r:group>

</r:SDPRules>
