=== Grandez/SDP_Java/SDPLoader/src/main/resources/SDPRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.sdp.com/SDPRules" 
           xmlns="http://www.sdp.com/SDPRules">

    <xs:element name="SDPRules">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="header" minOccurs="0" maxOccurs="1" />
               <xs:element ref="group"  minOccurs="0" maxOccurs="unbounded" />
               <xs:element ref="item"   minOccurs="0" maxOccurs="unbounded" />            
           </xs:sequence>
       </xs:complexType>
    </xs:element>

   <xs:element name="header">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="title"   type="xs:string"  minOccurs="0" maxOccurs="1" />
          <xs:element name="replace" type="xs:boolean" minOccurs="0" maxOccurs="1" default="true"/>
          <xs:element name="comment" type="xs:string"  minOccurs="0" maxOccurs="1" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <xs:element name="group">
        <xs:complexType>
    	   <xs:sequence>
               <xs:element name="idGroup"   type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="idParent"  type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="prefix"    type="prefixType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"    type="xs:boolean" minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="title"                        minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="description"                  minOccurs="0" maxOccurs="1"/>

               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>
               <xs:element name="sample"    type="sampleType" minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="item"                         minOccurs="0" maxOccurs="unbounded"  />
           </xs:sequence>
    	   <xs:attribute name="name"  type="nameType" use="required"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="idItem"  type="idType"      minOccurs="0" maxOccurs="1"/>
               <xs:element name="idGroup" type="idType"      minOccurs="0" maxOccurs="1"/>
               <xs:element name="object"  type="objectType"  minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"  type="xs:boolean"  minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="title"                       minOccurs="0" maxOccurs="1"/>
               <xs:element ref="description"                 minOccurs="0" maxOccurs="1"/>
               <xs:element ref="message"                     minOccurs="0" maxOccurs="1"/>
                                             
               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>

               <xs:element name="sample"  type="sampleType"  minOccurs="0" maxOccurs="1"/>
               <xs:element ref="rule"                        minOccurs="0" maxOccurs="unbounded" />
           </xs:sequence>
           <xs:attribute name="name"  type="nameType" use="required"/>
           
       </xs:complexType>
       
    </xs:element>

    <xs:element name="rule">
       <xs:complexType>
            <xs:sequence>
               <xs:element name="idRule"      type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="idItem"      type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="idGroup"     type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="priority"    type="xs:int"        minOccurs="0" maxOccurs="1"   default="0"/>
               <xs:element name="severity"    type="severityType"  minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"      type="xs:boolean"    minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="message"                           minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="description"                       minOccurs="0" maxOccurs="1"/>

               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>              
               <xs:element name="condition"   type="conditionType" minOccurs="0" maxOccurs="1"/>
               <xs:element name="sample"      type="sampleType"    minOccurs="0" maxOccurs="1"/>
           </xs:sequence>
           <xs:attribute name="name"  type="nameType"/>          
       </xs:complexType>
   </xs:element>         

  <xs:element name="message">
    <xs:complexType>
         <xs:sequence>     
            <xs:element name="text" type="textType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="description">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="1">
         <xs:element name="ref" type="idType"/>
         <xs:sequence>     
            <xs:element name="text" type="textType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
      </xs:choice>
      <xs:attribute name="id"  type="idType"  use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="title">
    <xs:complexType>
         <xs:sequence>     
            <xs:element name="text" type="titleType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
    </xs:complexType>
  </xs:element>

   <xs:complexType name="objectType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="type"  type="subObject"   use="optional"/>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

   <xs:complexType name="conditionTypeList">
      <xs:sequence>
          <xs:element name="condition" type="conditionType" minOccurs="1" maxOccurs="unbounded"  />
      </xs:sequence>
   </xs:complexType>
   
   <xs:complexType name="textType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="lang"    use="optional" default="xx"/>
            <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  
   <xs:complexType name="titleType">
       <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="lang"    use="optional" default="xx"/>
            <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
         </xs:extension>         
      </xs:simpleContent>
  </xs:complexType>
  
   <xs:simpleType name="severityType">
       <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="5"/>
       </xs:restriction>
   </xs:simpleType>


   <xs:complexType name="conditionType">
          <xs:sequence>
             <xs:element ref="message" minOccurs="0" maxOccurs="1"/>
             <xs:choice minOccurs="0" maxOccurs="1">
                 <xs:element name="lvalue"          type="operandType"/>
                 <xs:element name="script"          type="scriptType"/>
                 <xs:element name="type"            type="lvalueType"/>
                 <xs:element name="configuration"   type="xs:string"/>
             </xs:choice>
             <xs:element name="operator"            type="operatorType"  minOccurs="0" maxOccurs="1"/>      
             <xs:choice minOccurs="0" maxOccurs="1">
                 <xs:element name="property"        type="xs:string"/>
                 <xs:element name="attribute"       type="xs:string"/>
                 <xs:element name="method"          type="xs:string"/>
                 <xs:element name="expression"      type="xs:string"/>
                 <xs:element name="value"           type="xs:string"/>
                 <xs:element name="rvalue"          type="xs:string"/>
                 <xs:element name="rscript"         type="scriptType"/>                 
             </xs:choice>

         </xs:sequence>

      <xs:attribute name="negated" use="optional"   type="xs:boolean"  default="false"/>   
   </xs:complexType>

   <xs:simpleType name="subObject">
       <xs:restriction base="xs:string">
          <xs:enumeration value="verb"/>
          <xs:enumeration value="option"/>
          <xs:enumeration value="lvalue"/>
          <xs:enumeration value="rvalue"/>
          <xs:enumeration value="list"/>
       </xs:restriction>
   </xs:simpleType>
    
   <xs:simpleType name="lvalueType">
       <xs:restriction base="xs:string">
          <xs:enumeration value="string"/>
          <xs:enumeration value="integer"/>
          <xs:enumeration value="long"/>
          <xs:enumeration value="decimal"/>
          <xs:enumeration value="boolean"/>
          <xs:enumeration value="date"/>
          <xs:enumeration value="time"/>
          <xs:enumeration value="timestamp"/>          
          <xs:enumeration value="verb"/>
          <xs:enumeration value="option"/>
          <xs:enumeration value="lvalue"/>
          <xs:enumeration value="rvalue"/>
          <xs:enumeration value="value"/>
       </xs:restriction>
   </xs:simpleType>


   <xs:complexType name="operandType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="type" use="optional" default="value">
                <xs:simpleType>
                   <xs:restriction base="xs:string">
                      <xs:enumeration value="attribute"/>
                      <xs:enumeration value="configuration"/>
                      <xs:enumeration value="expression"/>
                      <xs:enumeration value="function"/>
                      <xs:enumeration value="method"/>
                      <xs:enumeration value="option"/>
                      <xs:enumeration value="property"/>                      
                      <xs:enumeration value="value"/>
                      <xs:enumeration value="variable"/>
                  </xs:restriction>
               </xs:simpleType>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
   
   <xs:simpleType name="operatorType">
      <xs:annotation>
         <xs:documentation>
             Comparator apply to object and value in form:
             object comparator value
             Comparator can be one of following keywords
                * ==       - Equal
                * >        - Greater than
                * &lt;        - Less than
                * >=       - Greater or equal than
                * &lt;=       - Less or equal than
                * start    - Object start with 'value' sequence
                * contains - Object contains 'value' sequence
                * match    - Object math the regular expression specified in 'value'
         </xs:documentation>
      </xs:annotation>
      <xs:union memberTypes="operatorTypeL operatorTypeU" />
   </xs:simpleType>


         <xs:simpleType name="operatorTypeL">
            <xs:restriction base="xs:string">
               <xs:enumeration value="mandatory"/>
               <xs:enumeration value="equal"/>
               <xs:enumeration value="eq"/>          
               <xs:enumeration value="is"/>          
               <xs:enumeration value="gt"/>
               <xs:enumeration value="lt"/>
               <xs:enumeration value="ge"/>
               <xs:enumeration value="le"/>
               <xs:enumeration value="start"/>
               <xs:enumeration value="end"/>
               <xs:enumeration value="contains"/>
               <xs:enumeration value="match"/>
               <xs:enumeration value="has"/>
           </xs:restriction>
       </xs:simpleType>
         <xs:simpleType name="operatorTypeU">
            <xs:restriction base="xs:string">
               <xs:enumeration value="MANDATORY"/>
               <xs:enumeration value="EQUAL"/>
               <xs:enumeration value="EQ"/>          
               <xs:enumeration value="IS"/>          
               <xs:enumeration value="GT"/>
               <xs:enumeration value="LT"/>
               <xs:enumeration value="GE"/>
               <xs:enumeration value="LE"/>
               <xs:enumeration value="START"/>
               <xs:enumeration value="END"/>
               <xs:enumeration value="CONTAINS"/>
               <xs:enumeration value="MATCH"/>
               <xs:enumeration value="HAS"/>
           </xs:restriction>
       </xs:simpleType>         

   <xs:complexType name="scriptType">
      <xs:sequence>
          <xs:element name="name"        type="xs:string"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="code"        type="xs:string"      minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>   
   </xs:complexType>

   <xs:complexType name="sampleType">
      <xs:sequence>
          <xs:element name="description" type="textType"       minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="correct"     type="xs:string"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="bad"         type="xs:string"      minOccurs="0" maxOccurs="1"/>
      </xs:sequence>   
   </xs:complexType>

   <xs:simpleType name="nameType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
      </xs:restriction>
  </xs:simpleType>
  
   <xs:simpleType name="prefixType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
         <xs:maxLength value="3" />
      </xs:restriction>
  </xs:simpleType>

   <xs:simpleType name="idType">
      <xs:restriction base="xs:long"/>
  </xs:simpleType>
  
</xs:schema>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1600_grp_div_id.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>IDENTIFICATION DIVISION</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="DIV_ID">
      <idGroup>16</idGroup>
      <idParent>15</idParent>
      <prefix>DIV</prefix>
      <active>true</active>
      <r:description>
          <text lang="xx">Reglas de control de procedure division</text>      
      </r:description>
      
      <r:item name="DIV_ID">
         <object>IDENTIFICATION</object>
         <active>true</active>
         <r:description id="1601">
             <text lang="xx">es necesario incluir la opcion {option}</text>      
         </r:description>
         
         <r:rule>
            <severity>2</severity>
            <condition>
               <lvalue type="option">INSTALLATION</lvalue>
               <property>has</property>
            </condition>        
         </r:rule>
         
         <r:rule>
            <severity>2</severity>
            <condition>
               <lvalue type="option">DATE-WRITTEN</lvalue>
               <property>has</property>
            </condition>        
         </r:rule>

         <r:rule>
            <severity>2</severity>
            <condition>
               <lvalue type="option">SECURITY</lvalue>
               <property>has</property>
            </condition>        
         </r:rule>

         <r:rule>
            <severity>2</severity>
            <condition negated="true">
               <lvalue type="option">DATE-COMPILED</lvalue>
               <property>has</property>
            </condition>        
         </r:rule>

         <r:rule>
            <severity>2</severity>
            <condition negated="true">
               <lvalue type="option">AUTHOR</lvalue>
               <property>has</property>
            </condition>        
         </r:rule>
         
      </r:item>

      <r:item name="DIV_AUTHOR">
         <object>AUTHOR</object>
         <onCondition>
            <lvalue type="option">AUTHOR</lvalue>
            <property>has</property>
         </onCondition>        
         <r:description>
             <text lang="xx">El autor debe seguir el patron "usuario - empresa"</text>      
         </r:description>
         
         <r:rule>
            <severity>3</severity>
            <condition>
               <operator>match</operator>
               <expression>[a-zA-Z0-9]{7} - [\w]+</expression>
            </condition>        
         </r:rule>

         <r:rule>
            <priority>3</priority>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Codificar la sentencia en la misma linea</text>      
            </r:description>
            <condition>
               <lvalue type="attribute">lines</lvalue>
               <operator>gt</operator>
               <expression>1</expression>
            </condition>        
         </r:rule>

         <r:rule>
            <priority>4</priority>
            <severity>2</severity>
            <r:description>
               <text lang="xx">Finalizar la sentencia con un punto</text>      
            </r:description>
            <condition negated="true">
               <lvalue type="attribute">hasEndOfSentence</lvalue>
            </condition>        
         </r:rule>
         
      </r:item>

      <r:item name="DIV_COMPILED">
         <object>DATE-COMPILED</object>
         <onCondition>
            <lvalue type="option">DATE-COMPILED</lvalue>
            <operator>has</operator>
          </onCondition>        
         
         <r:rule>
            <priority>1</priority>
            <severity>3</severity>
            <r:description>
               <text lang="xx">La fecha de compilacion debe estar en formato dd/mm/yyyy</text>      
            </r:description>
            <condition>
               <operator>match</operator>
               <expression>[0-9]{1,2}/[0-9]{1,2}/[0-9]{4}</expression>
            </condition>        
         </r:rule>

         <r:rule>
            <priority>2</priority>
            <severity>3</severity>
            <onCondition>
                <lvalue type="configuration">parser.force</lvalue>
                <operator>is</operator>
                <value>false</value>
            </onCondition>
            <r:description>
               <text lang="xx">La fecha de compilacion debe estar actualizada</text>      
            </r:description>
            <condition>
               <lvalue type="expression">now() - as.date({object})</lvalue>
               <operator>lt</operator>
               <expression>7</expression>
            </condition>        
         </r:rule>

         <r:rule>
            <priority>3</priority>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Codificar la sentencia en la misma linea</text>      
            </r:description>
            <condition>
               <lvalue type="attribute">lines</lvalue>
               <operator>gt</operator>
               <expression>1</expression>
            </condition>        
         </r:rule>

         <r:rule>
            <priority>4</priority>
            <severity>2</severity>
            <r:description>
               <text lang="xx">Finalizar la sentencia con un punto</text>      
            </r:description>
            <condition negated="true">
               <lvalue type="attribute">hasEndOfSentence</lvalue>
            </condition>        
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_5000_grp_par.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas de parrafos</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="PAR">
      <idGroup>50</idGroup>
      <prefix>PAR</prefix>
      <r:description>
          <text lang="xx">Calidad de parrafos</text>      
      </r:description>
      
      <r:item name="Inline">
         <object>PARAGRAPH</object>        
         <onCondition>
             <property>isInline()</property>
         </onCondition>            

         <r:description>
            <text lang="xx">Control de parrafos inline</text>
         </r:description>

         <r:rule>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Lineas del parrafo</text>
            </r:description>
            <condition>
               <lvalue type="attribute">numLines</lvalue>
               <operator>gt</operator>
               <rvalue>10</rvalue>
            </condition>            
         </r:rule>

         <r:rule>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Lineas del parrafo</text>
            </r:description>
            <condition>
               <lvalue type="attribute">numBlocks</lvalue>
               <operator>gt</operator>
               <rvalue>3</rvalue>
            </condition>            
         </r:rule>
         
      </r:item>
         
      <r:item name="Outline">
         <object>PARAGRAPH</object>        
         <onCondition>
            <property>isOutline()</property>
         </onCondition>
         <r:description>
            <text lang="xx">Control parrafos outline</text>
         </r:description>

         <r:rule>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Parrafos de EXIT</text>
            </r:description>
            <condition>
               <property>isExit()</property>
            </condition>            
         </r:rule>
         
         <r:rule>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Lineas del parrafo</text>
            </r:description>
            <condition>
               <lvalue type="attribute">numLines</lvalue>
               <operator>gt</operator>
               <rvalue>10</rvalue>
            </condition>            
         </r:rule>

         <r:rule>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Sentencias del parrafo</text>
            </r:description>
            <condition>
               <lvalue type="attribute">numStatements</lvalue>
               <operator>gt</operator>
               <rvalue>5</rvalue>
            </condition>            
         </r:rule>

         <r:rule>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Complejidad del parrafo</text>
            </r:description>
            <condition>
               <lvalue type="attribute">currentCC</lvalue>
               <operator>gt</operator>
               <rvalue>3</rvalue>
            </condition>            
         </r:rule>

      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_4200_grp_stmt_arit.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Instrucciones aritmeticas</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="STMTARIT">
      <idGroup>42</idGroup>
      <idParent>40</idParent>
      <prefix>STM</prefix>
      <r:title>
          <text lang="xx">Instrucciones aritmeticas</text>      
      </r:title>

      <r:description>
          <text lang="xx">Instrucciones aritmeticas</text>      
      </r:description>

      <onConditions>
         <condition>
            <lvalue type="property">groupName</lvalue>
            <value>COBOL</value>
          </condition>
         <condition>
            <lvalue type="property">subgroupName</lvalue>
            <value>ARIT</value>
          </condition>

      </onConditions>        
      
      <r:item name="RVALUES">
         <object>STATEMENT</object>
         <r:title>
            <text>Multiple RValues</text>      
         </r:title>

         <r:message>
            <text>No se recomienda utilizar operaciones aritmeticas sobre varios elementos</text>
         </r:message>
         
         <r:rule>
            <severity>3</severity>
            <condition>
               <lvalue type="property">numRValues</lvalue>
               <operator>gt</operator>
               <rvalue>1</rvalue>
            </condition>            
         </r:rule>

      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_7100_cics_stmt.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas CICS</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CICS_STMT">
      <idGroup>71</idGroup>
      <idParent>70</idParent>      
      <prefix>CIC</prefix>
      <r:title>
          <text>CICS No permitido</text>      
      </r:title>

      <r:item name="CICS_STMT">
         <object>STATEMENT</object>
         <r:title>
            <text>Sentencias CICS no permitidas</text>      
         </r:title>
         <r:message>
           <text>Sentencia CICS no permitida: **:Value:**</text>
         </r:message>
                 
         <r:rule>
            <severity>5</severity>
            <condition>
               <value>DISCARD</value>
            </condition>            
         </r:rule>
      </r:item>
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_9100_grp_rul.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas de control de issues</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="ISSUES">
      <idGroup>91</idGroup>    
      <idParent>90</idParent> 
      <prefix>ISS</prefix>
      <r:description>
          <text lang="xx">Reglas de control de los issues</text>      
      </r:description>
      
      <r:item name="Issues">
         <object>ISSUES</object>
        
         <r:description>
            <text lang="xx">El numero maximo de incidencias de nivel :IdRule: es de :Rvalue:</text>
         </r:description>
         <r:message>
            <text lang="xx">El numero maximo de incidencias de nivel :IdRule: es de :Rvalue:</text>
         </r:message>
         
         <r:rule>
            <severity>5</severity>
            <condition>
               <lvalue type="method">getNumIssues(0)</lvalue>
               <operator>gt</operator>
               <rvalue>5</rvalue>
            </condition>            
         </r:rule>
         
         <r:rule>
            <severity>5</severity>
            <condition>
               <lvalue type="method">getNumIssues(1)</lvalue>
               <operator>gt</operator>
               <rvalue>4</rvalue>
            </condition>            
         </r:rule>
         <r:rule>
            <severity>5</severity>
            <condition>
               <lvalue type="method">getNumIssues(2)</lvalue>
               <operator>gt</operator>
               <rvalue>3</rvalue>
            </condition>            
         </r:rule>
         <r:rule>
            <severity>5</severity>
            <condition>
               <lvalue type="method">getNumIssues(3)</lvalue>
               <operator>gt</operator>
               <rvalue>2</rvalue>
            </condition>            
         </r:rule>
         <r:rule>
            <severity>5</severity>
            <condition>
               <lvalue type="method">getNumIssues(4)</lvalue>
               <operator>gt</operator>
               <rvalue>1</rvalue>
            </condition>            
         </r:rule>
         <r:rule>
            <severity>5</severity>
            <condition>
               <lvalue type="method">getNumIssues(5)</lvalue>
               <operator>gt</operator>
               <rvalue>0</rvalue>
            </condition>            
         </r:rule>

         <r:rule>
            <idRule>10</idRule>
            <severity>5</severity>
            <condition>
               <script>
                  <name>Agrupacion de Issues</name>
                  <code>SUM({IssuesCounts} * ({IssuesLevels} + 1)) / (1 + SUM({IssuesCounts}))</code>
               </script>
               <operator>gt</operator>
               <rvalue>3</rvalue>
            </condition>            
         </r:rule>

      </r:item>
      
   </r:group>

</r:SDPRules>
