=== Grandez/SDP_Java/SDPLoader/src/main/resources/SDPRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.sdp.com/SDPRules" 
           xmlns="http://www.sdp.com/SDPRules">

    <xs:element name="SDPRules">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="header" minOccurs="0" maxOccurs="1" />
               <xs:element ref="group"  minOccurs="0" maxOccurs="unbounded" />
               <xs:element ref="item"   minOccurs="0" maxOccurs="unbounded" />            
           </xs:sequence>
       </xs:complexType>
    </xs:element>

   <xs:element name="header">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="title"   type="xs:string"  minOccurs="0" maxOccurs="1" />
          <xs:element name="replace" type="xs:boolean" minOccurs="0" maxOccurs="1" default="true"/>
          <xs:element name="comment" type="xs:string"  minOccurs="0" maxOccurs="1" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <xs:element name="group">
        <xs:complexType>
    	   <xs:sequence>
               <xs:element name="idGroup"   type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="idParent"  type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="prefix"    type="prefixType" minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"    type="xs:boolean" minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="title"                        minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="description"                  minOccurs="0" maxOccurs="1"/>

               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>
               <xs:element name="sample"    type="sampleType" minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="item"                         minOccurs="0" maxOccurs="unbounded"  />
           </xs:sequence>
    	   <xs:attribute name="name"  type="nameType" use="required"/>

        </xs:complexType>
    </xs:element>

    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
               <xs:element name="idItem"  type="idType"      minOccurs="0" maxOccurs="1"/>
               <xs:element name="idGroup" type="idType"      minOccurs="0" maxOccurs="1"/>
               <xs:element name="object"  type="objectType"  minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"  type="xs:boolean"  minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="title"                       minOccurs="0" maxOccurs="1"/>
               <xs:element ref="description"                 minOccurs="0" maxOccurs="1"/>
               <xs:element ref="message"                     minOccurs="0" maxOccurs="1"/>
                                             
               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>

               <xs:element name="sample"  type="sampleType"  minOccurs="0" maxOccurs="1"/>
               <xs:element ref="rule"                        minOccurs="0" maxOccurs="unbounded" />
           </xs:sequence>
           <xs:attribute name="name"  type="nameType" use="required"/>
           
       </xs:complexType>
       
    </xs:element>

    <xs:element name="rule">
       <xs:complexType>
            <xs:sequence>
               <xs:element name="idRule"      type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="idItem"      type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="idGroup"     type="idType"        minOccurs="0" maxOccurs="1"/>
               <xs:element name="priority"    type="xs:int"        minOccurs="0" maxOccurs="1"   default="0"/>
               <xs:element name="severity"    type="severityType"  minOccurs="1" maxOccurs="1"/>
               <xs:element name="active"      type="xs:boolean"    minOccurs="0" maxOccurs="1"   default="true"/>
               <xs:element ref="message"                           minOccurs="0" maxOccurs="1"/>               
               <xs:element ref="description"                       minOccurs="0" maxOccurs="1"/>

               <xs:choice minOccurs="0" maxOccurs="1">
                  <xs:element name="onCondition"  type="conditionType"/>
                  <xs:element name="onConditions" type="conditionTypeList" />
               </xs:choice>              
               <xs:element name="condition"   type="conditionType" minOccurs="0" maxOccurs="1"/>
               <xs:element name="sample"      type="sampleType"    minOccurs="0" maxOccurs="1"/>
           </xs:sequence>
           <xs:attribute name="name"  type="nameType"/>          
       </xs:complexType>
   </xs:element>         

  <xs:element name="message">
    <xs:complexType>
         <xs:sequence>     
            <xs:element name="text" type="textType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="description">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="1">
         <xs:element name="ref" type="idType"/>
         <xs:sequence>     
            <xs:element name="text" type="textType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
      </xs:choice>
      <xs:attribute name="id"  type="idType"  use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="title">
    <xs:complexType>
         <xs:sequence>     
            <xs:element name="text" type="titleType" minOccurs="1" maxOccurs="unbounded" />
         </xs:sequence>
    </xs:complexType>
  </xs:element>

   <xs:complexType name="objectType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="type"  type="subObject"   use="optional"/>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>

   <xs:complexType name="conditionTypeList">
      <xs:sequence>
          <xs:element name="condition" type="conditionType" minOccurs="1" maxOccurs="unbounded"  />
      </xs:sequence>
   </xs:complexType>
   
   <xs:complexType name="textType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="lang"    use="optional" default="xx"/>
            <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  
   <xs:complexType name="titleType">
       <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute type="xs:string" name="lang"    use="optional" default="xx"/>
            <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
         </xs:extension>         
      </xs:simpleContent>
  </xs:complexType>
  
   <xs:simpleType name="severityType">
       <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="5"/>
       </xs:restriction>
   </xs:simpleType>


   <xs:complexType name="conditionType">
          <xs:sequence>
             <xs:element ref="message" minOccurs="0" maxOccurs="1"/>
             <xs:choice minOccurs="0" maxOccurs="1">
                 <xs:element name="lvalue"          type="operandType"/>
                 <xs:element name="script"          type="scriptType"/>
                 <xs:element name="type"            type="lvalueType"/>
                 <xs:element name="configuration"   type="xs:string"/>
             </xs:choice>
             <xs:element name="operator"            type="operatorType"  minOccurs="0" maxOccurs="1"/>      
             <xs:choice minOccurs="0" maxOccurs="1">
                 <xs:element name="property"        type="xs:string"/>
                 <xs:element name="attribute"       type="xs:string"/>
                 <xs:element name="method"          type="xs:string"/>
                 <xs:element name="expression"      type="xs:string"/>
                 <xs:element name="value"           type="xs:string"/>
                 <xs:element name="rvalue"          type="xs:string"/>
                 <xs:element name="rscript"         type="scriptType"/>                 
             </xs:choice>

         </xs:sequence>

      <xs:attribute name="negated" use="optional"   type="xs:boolean"  default="false"/>   
   </xs:complexType>

   <xs:simpleType name="subObject">
       <xs:restriction base="xs:string">
          <xs:enumeration value="verb"/>
          <xs:enumeration value="option"/>
          <xs:enumeration value="lvalue"/>
          <xs:enumeration value="rvalue"/>
          <xs:enumeration value="list"/>
       </xs:restriction>
   </xs:simpleType>
    
   <xs:simpleType name="lvalueType">
       <xs:restriction base="xs:string">
          <xs:enumeration value="string"/>
          <xs:enumeration value="integer"/>
          <xs:enumeration value="long"/>
          <xs:enumeration value="decimal"/>
          <xs:enumeration value="boolean"/>
          <xs:enumeration value="date"/>
          <xs:enumeration value="time"/>
          <xs:enumeration value="timestamp"/>          
          <xs:enumeration value="verb"/>
          <xs:enumeration value="option"/>
          <xs:enumeration value="lvalue"/>
          <xs:enumeration value="rvalue"/>
          <xs:enumeration value="value"/>
       </xs:restriction>
   </xs:simpleType>


   <xs:complexType name="operandType">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="type" use="optional" default="value">
                <xs:simpleType>
                   <xs:restriction base="xs:string">
                      <xs:enumeration value="attribute"/>
                      <xs:enumeration value="configuration"/>
                      <xs:enumeration value="expression"/>
                      <xs:enumeration value="function"/>
                      <xs:enumeration value="method"/>
                      <xs:enumeration value="option"/>
                      <xs:enumeration value="property"/>                      
                      <xs:enumeration value="value"/>
                      <xs:enumeration value="variable"/>
                  </xs:restriction>
               </xs:simpleType>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
   
   <xs:simpleType name="operatorType">
      <xs:annotation>
         <xs:documentation>
             Comparator apply to object and value in form:
             object comparator value
             Comparator can be one of following keywords
                * ==       - Equal
                * >        - Greater than
                * &lt;        - Less than
                * >=       - Greater or equal than
                * &lt;=       - Less or equal than
                * start    - Object start with 'value' sequence
                * contains - Object contains 'value' sequence
                * match    - Object math the regular expression specified in 'value'
         </xs:documentation>
      </xs:annotation>
      <xs:union memberTypes="operatorTypeL operatorTypeU" />
   </xs:simpleType>


         <xs:simpleType name="operatorTypeL">
            <xs:restriction base="xs:string">
               <xs:enumeration value="mandatory"/>
               <xs:enumeration value="equal"/>
               <xs:enumeration value="eq"/>          
               <xs:enumeration value="is"/>          
               <xs:enumeration value="gt"/>
               <xs:enumeration value="lt"/>
               <xs:enumeration value="ge"/>
               <xs:enumeration value="le"/>
               <xs:enumeration value="start"/>
               <xs:enumeration value="end"/>
               <xs:enumeration value="contains"/>
               <xs:enumeration value="match"/>
               <xs:enumeration value="has"/>
           </xs:restriction>
       </xs:simpleType>
         <xs:simpleType name="operatorTypeU">
            <xs:restriction base="xs:string">
               <xs:enumeration value="MANDATORY"/>
               <xs:enumeration value="EQUAL"/>
               <xs:enumeration value="EQ"/>          
               <xs:enumeration value="IS"/>          
               <xs:enumeration value="GT"/>
               <xs:enumeration value="LT"/>
               <xs:enumeration value="GE"/>
               <xs:enumeration value="LE"/>
               <xs:enumeration value="START"/>
               <xs:enumeration value="END"/>
               <xs:enumeration value="CONTAINS"/>
               <xs:enumeration value="MATCH"/>
               <xs:enumeration value="HAS"/>
           </xs:restriction>
       </xs:simpleType>         

   <xs:complexType name="scriptType">
      <xs:sequence>
          <xs:element name="name"        type="xs:string"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="code"        type="xs:string"      minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>   
   </xs:complexType>

   <xs:complexType name="sampleType">
      <xs:sequence>
          <xs:element name="description" type="textType"       minOccurs="0" maxOccurs="unbounded"/>
          <xs:element name="correct"     type="xs:string"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="bad"         type="xs:string"      minOccurs="0" maxOccurs="1"/>
      </xs:sequence>   
   </xs:complexType>

   <xs:simpleType name="nameType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
      </xs:restriction>
  </xs:simpleType>
  
   <xs:simpleType name="prefixType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
         <xs:maxLength value="3" />
      </xs:restriction>
  </xs:simpleType>

   <xs:simpleType name="idType">
      <xs:restriction base="xs:long"/>
  </xs:simpleType>
  
</xs:schema>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_7000_grp_cics.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas CICS</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CICS">
      <idGroup>70</idGroup>
      <prefix>CIC</prefix>
      <r:title>
          <text>Calidad CICS</text>      
      </r:title>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1710_grp_div_env_conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>ENVIRONMENT DIVISION</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="DIV_ENV">
      <idGroup>171</idGroup>
      <idParent>17</idParent>
      <prefix>CFG</prefix>
      <active>true</active>
      <r:title>
          <text>CONFIGURATION SECTION</text>      
      </r:title>

      <r:description>
          <text lang="xx">Reglas de control de configuration section</text>      
      </r:description>
      
      <r:item name="SECT_CONF">
         <object>CONFIGURATION</object>
         <active>true</active>
         <r:title>
             <text>Opciones de CONFIGURATION SECTION</text>      
         </r:title>
         
         <r:description>
             <text lang="xx">
               SOURCE y OBJECT COMPUTER son unicamente informativos
               No es necesario indicarlos
             </text>      
         </r:description>
         <r:message>
                  <text lang="xx" dialect="XX">No es necesario indicar **:Lvalue:**</text>
         </r:message>
         
         <r:rule>
            <severity>2</severity>
            <condition>
               <lvalue type="option">SOURCE-COMPUTER</lvalue>
               <property>has</property>
            </condition>        
         </r:rule>
         
         <r:rule>
            <severity>2</severity>
            <condition>
               <lvalue type="option">OBJECT-COMPUTER</lvalue>
               <property>has</property>
            </condition>        
         </r:rule>

      </r:item>
      
      <r:item name="CONF_LINES">
         <object type="list">Option</object>
         <r:title>
             <text>Codificar en la misma linea</text>      
         </r:title>

         <r:rule name="lines">
            <priority>3</priority>
            <severity>3</severity>
            <r:description>
               <text lang="xx">Codificar las opciones en la misma linea</text>      
            </r:description>
            <condition>
               <lvalue type="attribute">lines</lvalue>
               <operator>gt</operator>
               <rvalue>1</rvalue>
            </condition>        
         </r:rule>
      </r:item>
      
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1500_grp_div.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas de control de las divisiones</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="DIV">
      <idGroup>15</idGroup>
      <prefix>DIV</prefix>
      <active>true</active>
      <r:description>
          <text lang="xx">Reglas de control de las divisiones</text>      
      </r:description>
      
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_1100_grp_dir.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Directivas de compilacion</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CBL">
      <idGroup>11</idGroup>
      <idParent>10</idParent>
      <prefix>CBL</prefix>
      <r:description>
          <text lang="xx">Directivas de compilacion</text>      
      </r:description>
      
      <r:item name="CBL_DIRECTIVE">
         <object>CBL</object>
         <r:description>
            <text lang="xx">No usar directivas de compilacion</text>
         </r:description>
         
         <r:rule>
            <severity>5</severity>
            <condition>
               <property>exist</property>
            </condition>            
         </r:rule>
         
      </r:item>

      <r:item name="CBL_LIST_DIRECTIVE">
         <object>WORD</object>
         <active>true</active>
         <r:description>
            <text lang="xx">No usar sentencias de compilacion</text>
         </r:description>
         
         <!--  Son logicamente excluyentes -->
         <r:rule name="eject">
            <priority>1</priority>
            <severity>3</severity>
            <condition>
               <value>EJECT</value>
            </condition>            
         </r:rule>

         <r:rule name="skip">
            <priority>1</priority>         
            <severity>3</severity>
            <condition>
               <value>SKIP</value>
            </condition>            
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_6100_sql_stmt.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas de SQL</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="DB2">
      <idGroup>61</idGroup>
      <idParent>60</idParent>      
      <prefix>SQL</prefix>
      <r:title>
          <text>SQL No permitido</text>      
      </r:title>

      <r:item name="DB2">
         <object>STATEMENT</object>
         <r:title>
            <text>SQL No permitido</text>      
         </r:title>
         <r:message>
           <text>En los programas no estan permitidas sentencias SQL de tipo :Group:</text>
         </r:message>
                 
         <r:rule>
            <severity>5</severity>            
            <condition>
               <lvalue type="attribute">subgroupName</lvalue>
               <operator>eq</operator>
               <rvalue>DCL</rvalue>
            </condition>            
         </r:rule>

         <r:rule>
            <severity>5</severity>            
            <condition>
               <lvalue type="attribute">subgroupName</lvalue>
               <operator>eq</operator>
               <rvalue>DDL</rvalue>
            </condition>            
         </r:rule>
      </r:item>
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_4200_grp_dir.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Directivas de codigo</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CBLDIR">
      <idGroup>42</idGroup>
      <idParent>40</idParent>
      <prefix>CBL</prefix>
      <r:title>
          <text lang="xx">Directivas de codigo</text>      
      </r:title>
      
      <r:item name="TRACE_DIRECTIVE">
         <object>STATEMENT</object>
         <active>true</active>
         <r:title>
            <text lang="xx">Directivas de codigo</text>      
         </r:title>
         <r:message>
            <text lang="xx">No usar directivas de traza</text>
         </r:message>
         
         <!--  Son logicamente excluyentes -->
         <r:rule name="ready">
            <priority>1</priority>
            <severity>3</severity>
            <condition>
               <value>READY</value>
            </condition>            
         </r:rule>

         <r:rule name="reset">
            <priority>1</priority>         
            <severity>3</severity>
            <condition>
               <value>RESET</value>
            </condition>            
         </r:rule>
         
      </r:item>

      <r:item name="REPLACE_DIRECTIVE">
         <object>STATEMENT</object>
         <active>true</active>
         <r:title>
            <text lang="xx">Directivas de codigo</text>      
         </r:title>
         <r:message>
            <text lang="xx">No usar macros replace</text>
         </r:message>
         
         <r:rule name="replace">
            <priority>1</priority>
            <severity>5</severity>
            <condition>
               <value>REPLACE</value>
            </condition>            
         </r:rule>

      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPLoader/src/main/resources/rules/rule_7200_cics_opt.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas CICS</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CICS_OPT">
      <idGroup>72</idGroup>
      <idParent>70</idParent>      
      <prefix>CIC</prefix>
      <r:title>
          <text>Calidad CICS</text>      
      </r:title>

      <r:item name="RESP">
         <object type="option">RESP</object>
         <r:title>
            <text>Control opcion RESP</text>      
         </r:title>
         <r:message>
           <text>Las sentencias CICS deben incluir la opcion **:Object:**</text>
         </r:message>
                 
         <r:rule>
            <severity>4</severity>
            <condition negated="true">
               <property>has</property>               
            </condition>        
         </r:rule>
       </r:item>

      <r:item name="NOHANDLE">
         <object type="option">NOHANDLE</object>
         <r:title>
            <text>Control opcion NOHANDLE</text>      
         </r:title>
                 
         <r:rule>
            <severity>4</severity>
            <condition>
               <r:message>
                 <text>Las sentencias CICS deben ser controladas</text>
               </r:message>
               <property>has</property>
            </condition>        
         </r:rule>
       </r:item>

   </r:group>

</r:SDPRules>
