=== Grandez/SDP_Java/SDPRules/src/main/resources/SDPRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.sdp.com/SDPRules" 
           xmlns="http://www.sdp.com/SDPRules">

    <xs:element name="SDPRules">
       <xs:complexType>
           <xs:sequence>
               <xs:element ref="header" minOccurs="0" maxOccurs="1" />
               <xs:element ref="group"  minOccurs="0" maxOccurs="unbounded" />
               <xs:element ref="item"   minOccurs="0" maxOccurs="unbounded" />            
           </xs:sequence>
       </xs:complexType>
    </xs:element>

   <xs:element name="header">
      <xs:complexType>
        <xs:sequence maxOccurs="unbounded">
          <xs:element name="title"   type="xs:string"  minOccurs="0" maxOccurs="1" />
          <xs:element name="replace" type="xs:boolean" minOccurs="0" maxOccurs="1" default="false"/>
          <xs:element name="comment" type="xs:string"  minOccurs="0" maxOccurs="1" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>

    <xs:element name="group">
        <xs:complexType>
    	   <xs:sequence>
    		   <xs:element name="idParent"  type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="idGroup"   type="idType"     minOccurs="0" maxOccurs="1"/>
    		   <xs:element name="prefix"    type="prefixType" minOccurs="1" maxOccurs="1"/>
    		   <xs:element name="active"    type="xs:boolean" minOccurs="0" maxOccurs="1"         default="true"/>
     		   <xs:element ref="description"                  minOccurs="0" maxOccurs="1"  />
               <xs:element ref="item"                         minOccurs="0" maxOccurs="unbounded"  />
           </xs:sequence>
    	   <xs:attribute name="name" type="nameType" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="idGroup" type="idType"     minOccurs="0" maxOccurs="1"/>
                <xs:element name="idItem"  type="idType"     minOccurs="0" maxOccurs="1"/>
                <xs:element name="object"  type="xs:string"  minOccurs="1" maxOccurs="1"/>
                <xs:choice                                   minOccurs="0" maxOccurs="1">
                    <xs:element name="active" type="xs:boolean"/>
                    <xs:element name="activateOnCondition" type="conditionType"/>
                </xs:choice>
                <xs:element ref="description"               minOccurs="0" maxOccurs="1"/>
                <xs:element ref="rule"                      minOccurs="0" maxOccurs="unbounded" />
           </xs:sequence>
           <xs:attribute type="xs:string" name="name" use="required"/>
       </xs:complexType>
    </xs:element>

    <xs:element name="rule">
       <xs:complexType>
            <xs:sequence>
                <xs:element name="idGroup"        type="idType"       minOccurs="0" maxOccurs="1"/>
                <xs:element name="idItem"         type="idType"       minOccurs="0" maxOccurs="1"/>
                <xs:element name="idRule"         type="idType"       minOccurs="0" maxOccurs="1"/>
                <xs:element name="priority"       type="xs:int"       minOccurs="0" maxOccurs="1"   default="0"/>
                <xs:element name="severity"       type="severityType" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description"                         minOccurs="0" maxOccurs="1"  />                
                <xs:choice minOccurs="0" maxOccurs="1">
                    <xs:element name="active" type="xs:boolean"/>
                    <xs:element name="activateOnCondition" type="conditionType"/>
                </xs:choice>
                <xs:element name="condition"      type="conditionType" minOccurs="0" maxOccurs="1"  />
                <xs:element name="sample"         type="sampleType"    minOccurs="0" maxOccurs="1"  />
           </xs:sequence>
       </xs:complexType>
   </xs:element>         

  <xs:element name="description">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id" type="idType" minOccurs="0" maxOccurs="1"></xs:element>      
        <xs:element ref="text" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

    <xs:element name="text">
       <xs:complexType>
           <xs:simpleContent>
              <xs:extension base="xs:string">
                  <xs:attribute type="xs:string" name="lang" use="optional" default="xx"/>
                  <xs:attribute type="xs:string" name="dialect" use="optional" default="XX"/>
              </xs:extension>
          </xs:simpleContent>
      </xs:complexType>
  </xs:element>
  
  <xs:element name="formula">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="id"         type="idType"      minOccurs="0" maxOccurs="1"/>      
        <xs:element name="type"       type="formulaType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="name"       type="xs:string"   minOccurs="1" maxOccurs="1"/>
        <xs:element name="definition" type="xs:string"   minOccurs="1" maxOccurs="1"/>
      </xs:sequence>  
    </xs:complexType>
  </xs:element>

   <xs:simpleType name="severityType">
       <xs:restriction base="xs:integer">
          <xs:minInclusive value="0"/>
          <xs:maxInclusive value="5"/>
       </xs:restriction>
   </xs:simpleType>

   <xs:simpleType name="formulaType">
       <xs:restriction base="xs:string">
          <xs:enumeration value="function"/>
          <xs:enumeration value="formula"/>
       </xs:restriction>
   </xs:simpleType>

   <xs:complexType name="conditionType">
      <xs:sequence>
          <xs:choice minOccurs="1" maxOccurs="1">
             <xs:element name="objectType"       type="objectType"/>
             <xs:element name="method"           type="xs:string"/>
             <xs:element name="expression"       type="expressionType"/>
          </xs:choice>
          <xs:element name="comparator"       type="comparatorType"  minOccurs="1" maxOccurs="1"/>
          <xs:element name="value"            type="xs:string"       minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="negated" use="optional" type="xs:boolean"/>   
   </xs:complexType>
   
   <xs:simpleType name="objectType">
       <xs:restriction base="xs:string">
          <xs:enumeration value="verb"/>
          <xs:enumeration value="word"/>
          <xs:enumeration value="option"/>
          <xs:enumeration value="lvalue"/>
          <xs:enumeration value="rvalue"/>
          <xs:enumeration value="value"/>
          <xs:enumeration value="special"/>
       </xs:restriction>
   </xs:simpleType>
   
   <xs:simpleType name="comparatorType">
      <xs:annotation>
         <xs:documentation>
             Comparator apply to object and value in form:
             object comparator value
             Comparator can be one of following keywords
                * ==       - Equal
                * >        - Greater than
                * &lt;        - Less than
                * >=       - Greater or equal than
                * &lt;=       - Less or equal than
                * start    - Object start with 'value' sequence
                * contains - Object contains 'value' sequence
                * match    - Object math the regular expression specified in 'value'
         </xs:documentation>
      </xs:annotation>
   
      <xs:restriction base="xs:string">
          <xs:enumeration value="mandatory"/>
          <xs:enumeration value="equal"/>
          <xs:enumeration value="gt"/>
          <xs:enumeration value="lt"/>
          <xs:enumeration value="ge"/>
          <xs:enumeration value="le"/>
          <xs:enumeration value="start"/>
          <xs:enumeration value="end"/>
          <xs:enumeration value="contains"/>
          <xs:enumeration value="match"/>
      </xs:restriction>
   </xs:simpleType>

   <xs:complexType name="sampleType">
      <xs:choice maxOccurs="unbounded">
          <xs:element name="correct"   type="xs:string"      minOccurs="0" maxOccurs="1"/>
          <xs:element name="bad"       type="xs:string"      minOccurs="0" maxOccurs="1"/>
      </xs:choice>   
   </xs:complexType>

   <xs:complexType name="expressionType">
      <xs:sequence>
          <xs:element name="code"      type="xs:string"      minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name" use="required"/>   
   </xs:complexType>
   
   <xs:simpleType name="nameType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
      </xs:restriction>
  </xs:simpleType>
  
   <xs:simpleType name="prefixType">
      <xs:restriction base="xs:string">
         <xs:minLength value="3" />
         <xs:maxLength value="3" />
      </xs:restriction>
  </xs:simpleType>

   <xs:simpleType name="idType">
      <xs:restriction base="xs:long"/>
  </xs:simpleType>
  
</xs:schema>

=== Grandez/SDP_Java/SDPRules/src/main/resources/rules/rule_9000_grp_mod.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas a nivel modulo</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="MOD">
      <idGroup>90</idGroup>     
      <prefix>MOD</prefix>
      <r:description>
          <text lang="xx">Reglas globales del modulo</text>      
      </r:description>
      
      <r:item name="ModuleName">
         <object>MODULE</object>
         <active>true</active>         
         <r:description>
            <text lang="xx">El nombre del ejecutable debe coincidir con el del fichero fuente</text>
         </r:description>
         
         <r:rule>
            <severity>5</severity>
            <condition>
               <attribute>moduleName</attribute>
               <operator>equal</operator>
               <rvalue type="method">fileName</rvalue>
            </condition>            
         </r:rule>
      </r:item>
      
      <r:item name="ModuleCount">
         <object>MODULE</object>
         <active>true</active>         
         <r:description>
            <text lang="xx">Cada ejecutable se codifica en su propio fichero fuente</text>
         </r:description>
         
         <r:rule>
            <severity>5</severity>
            <condition>
               <attribute>moduleCount</attribute>
               <operator>equal</operator>
               <rvalue>1</rvalue>
            </condition>            
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPRules/src/main/resources/rules/rule_1200_grp_cmt.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas lexicas / Comentarios</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CMT">
      <idGroup>12</idGroup>
      <idParent>10</idParent>
      <prefix>CMT</prefix>
      <active>true</active>
      <r:description>
          <text lang="xx">Comentarios</text>      
      </r:description>
      
      <r:item name="CMT">
         <object>CMT</object>
         <active>true</active>
         <r:description>
            <text lang="xx">Gestion de comentarios</text>
         </r:description>
         
         <r:rule>
            <severity>2</severity>
            <r:description>
               <text lang="xx">Los comentarios {comparator} {value}</text>
            </r:description>
            <condition negated="true">
               <type>string</type>
               <operator>start</operator>
               <rvalue>*</rvalue>
            </condition>        
            <sample>
               <description lang="xx">
               Los comentarios pueden empezar con *,/ o D
               
               Estos dos ultimos afectan a como se imprime el codigo fuente durante la fase de compilacion.   
               Dado que no esta permitido imprimir listados desde el Host, estos tipos de comentarios no deben
               utilizarse
               </description> 
               <correct>
      * ESTE ES UN COMENTARIO CORRECTO           
               </correct>
                            
               <bad>
      / ESTE ES UN COMENTARIO INCORRECTO
      D ESTE ES OTRO COMENTARIO INCORRECTO          
               </bad>

            </sample>                
         </r:rule>
         
         <r:rule>
            <severity>2</severity>
            <r:description>
               <text lang="xx">No se deben crear lineas de comentarios aislados</text>
            </r:description>
            <condition>
               <attribute>length</attribute>
               <operator>equal</operator>
               <rvalue>1</rvalue>
            </condition>        
                
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPRules/src/main/resources/rules/rule_1100_grp_dir.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Directivas de compilacion</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="CBL">
      <idGroup>11</idGroup>
      <idParent>10</idParent>
      <prefix>CBL</prefix>
      <r:description>
          <text lang="xx">Directivas de compilacion</text>      
      </r:description>
      
      <r:item name="CBL">
         <object>CBL</object>
         <r:description>
            <text lang="xx">No usar directivas de compilacion</text>
         </r:description>
         
         <r:rule>
            <severity>5</severity>
            <condition negated="true">
               <property>exist()</property>
            </condition>            
         </r:rule>
         
      </r:item>

      <r:item name="RES">
         <object>WORD</object>
         <active>true</active>
         <r:description>
            <text lang="xx">No usar sentencias de compilacion</text>
         </r:description>
         
         <r:rule>
            <severity>3</severity>
            <condition>
               <type>string</type>
               <operator>equal</operator>
               <rvalue>EJECT</rvalue>
            </condition>            
         </r:rule>

         <r:rule>
            <severity>3</severity>
            <condition>
               <type>string</type>
               <operator>equal</operator>
               <rvalue>SKIP</rvalue>
            </condition>            
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPRules/src/main/resources/rules/rule_1000_grp_lex.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Reglas lexicas</title>
      <replace>false</replace>
   </r:header>
   
   <r:group name="LEX">
      <idParent>0</idParent>
      <idGroup>10</idGroup>
      <prefix>LEX</prefix>
      <active>true</active>
      <r:description>
          <r:text lang="xx">Analisis lexico</r:text>      
      </r:description>
      
      <r:item name="TAB">
         <idItem>1</idItem>
         <active>true</active>
         <object>TAB</object>
         <r:description>
            <r:text lang="xx">No usar caracteres de tabulacion</r:text>
         </r:description>
         
         <r:rule>
            <idRule>1</idRule>
            <active>true</active>
            <priority>0</priority>
            <severity>2</severity>
            <r:description>
               <r:text lang="xx">No usar caracteres de tabulacion</r:text>
            </r:description>
            <condition negated="true">
               <objectType>word</objectType>
               <comparator>mandatory</comparator>
               <value>\t</value>
            </condition>            
         </r:rule>
      </r:item>

      <r:item name="HEX">
         <idItem>2</idItem>
         <active>true</active>
         <object>HEX</object>
            <r:description>
               <r:text lang="xx">Usar la codificacion hexadecimal para los caracteres no imprimibles</r:text>
            </r:description>
            
         <r:rule>
            <idRule>2</idRule>
            <active>true</active>
            <priority>0</priority>
            <severity>2</severity>
            <r:description>
               <r:text lang="xx">Usar la codificacion hexadecimal para los caracteres no imprimibles</r:text>
            </r:description>
            <condition negated="true">
               <objectType>word</objectType>
               <comparator>mandatory</comparator>
               <value>0x10</value>
            </condition>            
            <sample>
               <bad>
        01  NON-PRINTABLE.
            03 TAB-CODE    PIC X(01) VALUE '\t'.           
               </bad>
               <correct>
        01  NON-PRINTABLE.
            03 TAB-CODE    PIC X(01) VALUE X'05'.           
               </correct>

            </sample>
         </r:rule>         
      </r:item>
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPRules/src/main/resources/rules/rule_0000_grp_sdp.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd">

   <r:header>
      <title>Raiz de las reglas</title>
      <replace>false</replace>
   </r:header>
   
   <r:group name="SDP">
      <idGroup>0</idGroup>
      <prefix>SDP</prefix>
      <active>true</active>
      <r:description>
          <r:text lang="xx">Raiz de las reglas</r:text>      
      </r:description>
   </r:group>

</r:SDPRules>

=== Grandez/SDP_Java/SDPRules/src/main/resources/rules/rule_4000_grp_stm.xml
<?xml version="1.0" encoding="UTF-8"?>
<r:SDPRules xmlns:r="http://www.sdp.com/SDPRules" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.sdp.com/SDPRules ../SDPRules.xsd ">

   <r:header>
      <title>Instrucciones no permitidas</title>
      <replace>true</replace>
   </r:header>
   
   <r:group name="STMT">
      <idGroup>40</idGroup>
      <prefix>STM</prefix>
      <r:description>
          <text lang="xx">Instrucciones no permitidas</text>      
      </r:description>
      
      <r:item name="STMT">
         <object>STATEMENT</object>
         
         <r:rule>
            <severity>5</severity>
            <condition>
               <type>string</type>
               <operator>equal</operator>
               <rvalue>GOTO</rvalue>
            </condition>            
         </r:rule>

         <r:rule>
            <severity>5</severity>
            <condition>
               <type>string</type>
               <operator>equal</operator>
               <rvalue>DISPLAY</rvalue>
            </condition>            
         </r:rule>
         
      </r:item>

   </r:group>

</r:SDPRules>
